### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by zhucute1** [CodeAsPoetry/PublicOpinion#1]
您好，打扰了，在学习您这个项目的过程中，找不到部分数据，因此无法把代码跑起来，您有空的话方便留下您的邮箱吗？我的邮箱是2601307363@qq.com.非常期待您的联系，非常感谢！

**Comment by zhucute1** [comment]
您好，打扰了，非常希望您能联系我，非常感谢！

**Comment by Black-wingsvV** [comment]
我也是没有拿到数据

**Comment by Black-wingsvV** [comment]
你这个数据是什么样字的格式呢
我去网上自己下载

**Comment by CodeAsPoetry** [comment]
不好意思哈，这个项目是当时在校研究课题，稍等几天，笔者最近把这个重构一下，代码、数据、能跑起来的Demo一起挂上去，谢谢大家的关注

**Comment by DefuLi** [comment]
现在能跑起来了吗老哥？

**Comment by Black-wingsvV** [comment]
> 现在能跑起来了吗老哥？

反正最后我清洗了数据 ，找到了解决方案

**Comment by zhucute1** [comment]
后来没关注，谢谢啦！老哥！感恩------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Black-wingsvV&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月8日(星期一) 中午12:04
收件人:&nbsp;&quot;CodeAsPoetry/PublicOpinion&quot;<PublicOpinion@noreply.github.com&gt;;
抄送:&nbsp;&quot;zhucute1&quot;<2601307363@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodeAsPoetry/PublicOpinion] 代码问题 (#1)

**Comment by CodeAsPoetry** [comment]
数据已上传，https://github.com/CodeAsPoetry/PublicOpinion/blob/master/data/%E8%AF%AD%E6%96%99.rar ，

包含网上收集的情感极性正负各 60000 ，共计 12w 的微博数据，以及抓取到的带有情感极性明显的新闻评论数据，后期此项目工程会进行完整全面重构，希望能够帮到大家。

**Comment by yingnie696969** [comment]
你好，打扰了，想问下这个项目主要用的是什么技术呢？

**Comment by Black-wingsvV** [comment]
具体的不怎么记得了，这个是情感分析的数据处理吧，用的应该TF-IDF，特征值提取




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodeAsPoetry/PublicOpinion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CodeAsPoetry/PublicOpinion] 代码问题 (#1)





 
你好，打扰了，想问下这个项目主要用的是什么技术呢？

**Comment by CodeAsPoetry** [comment]
目前代码中还是几年前的老代码，主要是数据处理，以及特征工程获取词向量。后续会把整体的代码更新上去。

**Comment by yingnie696969** [comment]
您好，请问方便问一下我该如何把项目跑起来吗？我直接用了pycharm打开，刚开始学习，研究了一天没有看明白，看reademe部分也看得不是很明白该怎么做，没办法才想着发邮件询问一下您，如果有打扰请见谅！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月15日(周三) 中午11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CodeAsPoetry/PublicOpinion] 代码问题 (#1)




 具体的不怎么记得了，这个是情感分析的数据处理吧，用的应该TF-IDF，特征值提取 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "CodeAsPoetry/PublicOpinion"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年6月15日(星期三) 中午11:07 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CodeAsPoetry/PublicOpinion] 代码问题 (#1) 
 
 
 
 
 
   
 你好，打扰了，想问下这个项目主要用的是什么技术呢？

**Comment by Black-wingsvV** [comment]
用jupternootbook




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodeAsPoetry/PublicOpinion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 晚上10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CodeAsPoetry/PublicOpinion] 代码问题 (#1)





 您好，请问方便问一下我该如何把项目跑起来吗？我直接用了pycharm打开，刚开始学习，研究了一天没有看明白，看reademe部分也看得不是很明白该怎么做，没办法才想着发邮件询问一下您，如果有打扰请见谅！ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年6月15日(周三) 中午11:10 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [CodeAsPoetry/PublicOpinion] 代码问题 (#1) 
 
 
 
 
  具体的不怎么记得了，这个是情感分析的数据处理吧，用的应该TF-IDF，特征值提取  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "CodeAsPoetry/PublicOpinion"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年6月15日(星期三) 中午11:07  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [CodeAsPoetry/PublicOpinion] 代码问题 (#1)  
   
   
   
   
   
     
  你好，打扰了，想问下这个项目主要用的是什么技术呢？

**Comment by CodeAsPoetry** [comment]
老代码没有必要跑起来了，里面也没有太多值得复现的地方，新的代码后续会陆续跟上去，包括数据处理、模型训练推理，可视化的工具等，如果有兴趣，后续可以跟进一下。ReadMe 部分目前主要是工程项目角度，确实不太友好。如果上手 NLP，建议跟进李沐大佬的 https://github.com/mli/paper-reading ， 工程的话，可能给不到太多建议，笔者自己是用到什么看什么，总之很感谢对项目的关注。
